// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package netty.test.message;

/**
 * Protobuf enum {@code EnumTest}
 */
public enum EnumTest
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ZERO = 0;</code>
   */
  ZERO(0),
  /**
   * <code>ONE = 1;</code>
   */
  ONE(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ZERO = 0;</code>
   */
  public static final int ZERO_VALUE = 0;
  /**
   * <code>ONE = 1;</code>
   */
  public static final int ONE_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EnumTest valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static EnumTest forNumber(int value) {
    switch (value) {
      case 0: return ZERO;
      case 1: return ONE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EnumTest>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EnumTest> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EnumTest>() {
          public EnumTest findValueByNumber(int number) {
            return EnumTest.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return netty.test.message.TestProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final EnumTest[] VALUES = values();

  public static EnumTest valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private EnumTest(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:EnumTest)
}

