// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package netty.test.message;

public final class TestProto {
  private TestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Student_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Student_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Test_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Test_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Test2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Test2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\"#\n\007Student\022\n\n\002id\030\001 \001(\005\022\014\n\004n" +
      "ame\030\002 \001(\t\"\235\001\n\004Test\022\n\n\002id\030\001 \001(\003\022\013\n\003sex\030\002 " +
      "\001(\005\022\014\n\004name\030\003 \001(\t\022\021\n\tfloatTest\030\004 \001(\002\022\022\n\n" +
      "doubleTest\030\005 \001(\001\022\025\n\003stu\030\006 \001(\0132\010.Student\022" +
      "\026\n\003enu\030\007 \001(\0162\t.EnumTest\022\014\n\004flag\030\t \001(\010\022\n\n" +
      "\002bs\030\n \001(\014\"\236\001\n\005Test2\022\n\n\002id\030\001 \001(\003\022\013\n\003sex\030\002" +
      " \001(\005\022\014\n\004name\030\003 \001(\t\022\021\n\tfloatTest\030\004 \001(\002\022\022\n" +
      "\ndoubleTest\030\005 \001(\001\022\025\n\003stu\030\006 \001(\0132\010.Student" +
      "\022\026\n\003enu\030\007 \001(\0162\t.EnumTest\022\014\n\004flag\030\t \001(\010\022\n" +
      "\n\002bs\030\n \001(\014*\035\n\010EnumTest\022\010\n\004ZERO\020\000\022\007\n\003ONE\020" +
      "\001B!\n\022netty.test.messageB\tTestProtoP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Student_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_Test_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Test_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Test_descriptor,
        new java.lang.String[] { "Id", "Sex", "Name", "FloatTest", "DoubleTest", "Stu", "Enu", "Flag", "Bs", });
    internal_static_Test2_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Test2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Test2_descriptor,
        new java.lang.String[] { "Id", "Sex", "Name", "FloatTest", "DoubleTest", "Stu", "Enu", "Flag", "Bs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
