// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package netty.test.message;

public interface Test2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:Test2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * long类型
   * </pre>
   *
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <pre>
   * int类型
   * </pre>
   *
   * <code>int32 sex = 2;</code>
   * @return The sex.
   */
  int getSex();

  /**
   * <pre>
   * 字符串类型
   * </pre>
   *
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * 字符串类型
   * </pre>
   *
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * float类型
   * </pre>
   *
   * <code>float floatTest = 4;</code>
   * @return The floatTest.
   */
  float getFloatTest();

  /**
   * <pre>
   * double类型
   * </pre>
   *
   * <code>double doubleTest = 5;</code>
   * @return The doubleTest.
   */
  double getDoubleTest();

  /**
   * <pre>
   * 自定义类型
   * </pre>
   *
   * <code>.Student stu = 6;</code>
   * @return Whether the stu field is set.
   */
  boolean hasStu();
  /**
   * <pre>
   * 自定义类型
   * </pre>
   *
   * <code>.Student stu = 6;</code>
   * @return The stu.
   */
  netty.test.message.Student getStu();
  /**
   * <pre>
   * 自定义类型
   * </pre>
   *
   * <code>.Student stu = 6;</code>
   */
  netty.test.message.StudentOrBuilder getStuOrBuilder();

  /**
   * <pre>
   * 枚举类型
   * </pre>
   *
   * <code>.EnumTest enu = 7;</code>
   * @return The enum numeric value on the wire for enu.
   */
  int getEnuValue();
  /**
   * <pre>
   * 枚举类型
   * </pre>
   *
   * <code>.EnumTest enu = 7;</code>
   * @return The enu.
   */
  netty.test.message.EnumTest getEnu();

  /**
   * <pre>
   * boolean类型
   * </pre>
   *
   * <code>bool flag = 9;</code>
   * @return The flag.
   */
  boolean getFlag();

  /**
   * <pre>
   * byteString类型
   * </pre>
   *
   * <code>bytes bs = 10;</code>
   * @return The bs.
   */
  com.google.protobuf.ByteString getBs();
}
