// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test1.proto

package netty.test.message.test;

/**
 * Protobuf type {@code Test1}
 */
public final class Test1 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Test1)
    Test1OrBuilder {
private static final long serialVersionUID = 0L;
  // Use Test1.newBuilder() to construct.
  private Test1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Test1() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Test1();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Test1(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            aaa_ = input.readInt32();
            break;
          }
          case 16: {

            bbb_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return netty.test.message.test.TestProto.internal_static_Test1_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return netty.test.message.test.TestProto.internal_static_Test1_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            netty.test.message.test.Test1.class, netty.test.message.test.Test1.Builder.class);
  }

  public static final int AAA_FIELD_NUMBER = 1;
  private int aaa_;
  /**
   * <code>int32 aaa = 1;</code>
   * @return The aaa.
   */
  @java.lang.Override
  public int getAaa() {
    return aaa_;
  }

  public static final int BBB_FIELD_NUMBER = 2;
  private long bbb_;
  /**
   * <code>int64 bbb = 2;</code>
   * @return The bbb.
   */
  @java.lang.Override
  public long getBbb() {
    return bbb_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (aaa_ != 0) {
      output.writeInt32(1, aaa_);
    }
    if (bbb_ != 0L) {
      output.writeInt64(2, bbb_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (aaa_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, aaa_);
    }
    if (bbb_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, bbb_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof netty.test.message.test.Test1)) {
      return super.equals(obj);
    }
    netty.test.message.test.Test1 other = (netty.test.message.test.Test1) obj;

    if (getAaa()
        != other.getAaa()) return false;
    if (getBbb()
        != other.getBbb()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AAA_FIELD_NUMBER;
    hash = (53 * hash) + getAaa();
    hash = (37 * hash) + BBB_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBbb());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static netty.test.message.test.Test1 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static netty.test.message.test.Test1 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static netty.test.message.test.Test1 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static netty.test.message.test.Test1 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static netty.test.message.test.Test1 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static netty.test.message.test.Test1 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static netty.test.message.test.Test1 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static netty.test.message.test.Test1 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static netty.test.message.test.Test1 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static netty.test.message.test.Test1 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static netty.test.message.test.Test1 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static netty.test.message.test.Test1 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(netty.test.message.test.Test1 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Test1}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Test1)
      netty.test.message.test.Test1OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return netty.test.message.test.TestProto.internal_static_Test1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return netty.test.message.test.TestProto.internal_static_Test1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              netty.test.message.test.Test1.class, netty.test.message.test.Test1.Builder.class);
    }

    // Construct using netty.test.message.test.Test1.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      aaa_ = 0;

      bbb_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return netty.test.message.test.TestProto.internal_static_Test1_descriptor;
    }

    @java.lang.Override
    public netty.test.message.test.Test1 getDefaultInstanceForType() {
      return netty.test.message.test.Test1.getDefaultInstance();
    }

    @java.lang.Override
    public netty.test.message.test.Test1 build() {
      netty.test.message.test.Test1 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public netty.test.message.test.Test1 buildPartial() {
      netty.test.message.test.Test1 result = new netty.test.message.test.Test1(this);
      result.aaa_ = aaa_;
      result.bbb_ = bbb_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof netty.test.message.test.Test1) {
        return mergeFrom((netty.test.message.test.Test1)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(netty.test.message.test.Test1 other) {
      if (other == netty.test.message.test.Test1.getDefaultInstance()) return this;
      if (other.getAaa() != 0) {
        setAaa(other.getAaa());
      }
      if (other.getBbb() != 0L) {
        setBbb(other.getBbb());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      netty.test.message.test.Test1 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (netty.test.message.test.Test1) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int aaa_ ;
    /**
     * <code>int32 aaa = 1;</code>
     * @return The aaa.
     */
    @java.lang.Override
    public int getAaa() {
      return aaa_;
    }
    /**
     * <code>int32 aaa = 1;</code>
     * @param value The aaa to set.
     * @return This builder for chaining.
     */
    public Builder setAaa(int value) {
      
      aaa_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 aaa = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAaa() {
      
      aaa_ = 0;
      onChanged();
      return this;
    }

    private long bbb_ ;
    /**
     * <code>int64 bbb = 2;</code>
     * @return The bbb.
     */
    @java.lang.Override
    public long getBbb() {
      return bbb_;
    }
    /**
     * <code>int64 bbb = 2;</code>
     * @param value The bbb to set.
     * @return This builder for chaining.
     */
    public Builder setBbb(long value) {
      
      bbb_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 bbb = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBbb() {
      
      bbb_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Test1)
  }

  // @@protoc_insertion_point(class_scope:Test1)
  private static final netty.test.message.test.Test1 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new netty.test.message.test.Test1();
  }

  public static netty.test.message.test.Test1 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Test1>
      PARSER = new com.google.protobuf.AbstractParser<Test1>() {
    @java.lang.Override
    public Test1 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Test1(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Test1> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Test1> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public netty.test.message.test.Test1 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

