// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test1.proto

package netty.test.message.test;

public interface Test1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:Test1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 aaa = 1;</code>
   * @return The aaa.
   */
  int getAaa();

  /**
   * <code>int64 bbb = 2;</code>
   * @return The bbb.
   */
  long getBbb();
}
